### ISSUE TITLE
calculation results

### ISSUE THREAD

**Issue by davidmatten** [Code4SA/Domestic-Workers#20]
On both http://living-wage.co.za/
and http://living-wage.news24.com/wageCalc.html
If you enter that you pay the minimum, and set costs to the maximum, the result returned is that the minimum wage is being paid.
See the attached screen shots.
Tested on mobile: Android 5.1.1. Chrome 45.0.2454.94.
Tested on Ubuntu, 14.04.3 LTS with Firefox 40.0.3.

![screenshot_2015-09-29-15-15-28](https://cloud.githubusercontent.com/assets/7010911/10174060/0f02b9ea-66e8-11e5-9e77-d3de8e9a0535.png)
![min_wage](https://cloud.githubusercontent.com/assets/7010911/10174133/7daa5470-66e8-11e5-9d59-94d2db0398ab.png)

**Comment by adieyal** [comment]
The real question is why are you paying your domestic worker so little
since she is clearly living the high life?

I wasn't able to re-create the bug on living-wage.co.za but I could on the
News24 site. Would you mind checking again? We don't have access to the
News24 site unfortunately so we can't fix it.

Adi

On Tue, Sep 29, 2015 at 8:27 PM, David Matten notifications@github.com
wrote:

> On both http://living-wage.co.za/
> and http://living-wage.news24.com/wageCalc.html
> If you enter that you pay the minimum, and set costs to the maximum, the
> result returned is that the minimum wage is being paid.
> See the attached screen shots.
> Tested on mobile: Android 5.1.1. Chrome 45.0.2454.94.
> Tested on Ubuntu, 14.04.3 LTS with Firefox 40.0.3.
> 
> [image: screenshot_2015-09-29-15-15-28]
> https://cloud.githubusercontent.com/assets/7010911/10174060/0f02b9ea-66e8-11e5-9e77-d3de8e9a0535.png
> [image: min_wage]
> https://cloud.githubusercontent.com/assets/7010911/10174133/7daa5470-66e8-11e5-9d59-94d2db0398ab.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Code4SA/Domestic-Workers/issues/20.

## 

Adi Eyal
Director
Code for South Africa
Promoting informed decision-making

phone: +27 78 014 2469
skype: adieyalcas
linkedin: http://za.linkedin.com/pub/dir/Adi/Eyal
web: http://www.code4sa.org
twitter: @soapsudtycoon

Follow us on twitter at @code4sa
For more information on how to participate in the open data community in
South Africa, go to: http://www.code4sa.org/#community
Sign up for Naked Data, our weekly round-up of what's happening locally and
internationally in data journalism and data visualisation. Register here:
http://www.code4sa.org/newsletter

**Comment by davidmatten** [comment]
Tested again on ubuntu with firefox (versions same as before)
Same result. (see screen shot, with date and time in top right)

![living_wage](https://cloud.githubusercontent.com/assets/7010911/10189953/c16aa6fc-6769-11e5-920e-5c2661ed7844.png)

And on Chrome Version 45.0.2454.101 (64-bit)

![living_wage_chrome](https://cloud.githubusercontent.com/assets/7010911/10190027/2d16fa86-676a-11e5-8c40-ed1b2f811574.png)
